In [2]:
import torch
import numpy as np

In [16]:
data=np.array([1,2,3])

In [17]:
t1=torch.Tensor(data)
t2=torch.tensor(data)
t3=torch.as_tensor(data)
t4=torch.from_numpy(data)

In [18]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [19]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [20]:
torch.get_default_dtype()

torch.float32

In [21]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [23]:
torch.tensor(np.array([1,2,3]),dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [24]:
data=np.array([1,2,3])
data

array([1, 2, 3])

In [25]:
t1=torch.Tensor(data)
t2=torch.tensor(data)
t3=torch.as_tensor(data)
t4=torch.from_numpy(data)

In [26]:
data[0]=0
data[2]=0
data[1]=0

In [27]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


In [3]:
#10
t=torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
],dtype=torch.float32)

In [5]:
t.size()

torch.Size([3, 4])

In [6]:
t.shape

torch.Size([3, 4])

In [7]:
len(t.shape)

2

In [8]:
torch.tensor(t.shape).prod()

tensor(12)

In [9]:
t.numel()

12

In [10]:
t.reshape([12,1])

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [11]:
t.reshape([2,6])

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [14]:
def flatten(t):
    t=t.reshape(1,-1)
    t=t.squeeze()
    return t

In [16]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [17]:
t1=torch.tensor([
    [1,2],
    [3,4]
])

In [18]:
t2=torch.tensor([
    [5,6],
    [7,8]
])

In [19]:
torch.cat((t1,t2),dim=0)


tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

[1, 3, 5, 7, 9]